'use client'

import { Header } from '@/components/header'
import { Footer } from '@/components/footer'
import { Button } from '@/components/ui/button'
import { ArrowLeft, Printer } from 'lucide-react'
import Link from 'next/link'

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <main className="pt-24 pb-16">
        <div className="container-max section-padding">
          <div className="max-w-4xl mx-auto">
            {/* Header */}
            <div className="mb-8 space-y-4">
              <Link href="/">
                <Button variant="ghost" size="sm" className="gap-2">
                  <ArrowLeft className="w-4 h-4" />
                  Back to Home
                </Button>
              </Link>
              
              <div className="flex items-start justify-between">
                <div>
                  <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
                  <p className="text-muted-foreground">Last updated: January 1, 2024</p>
                </div>
                
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => window.print()}
                  className="hidden md:flex gap-2"
                >
                  <Printer className="w-4 h-4" />
                  Print
                </Button>
              </div>
            </div>

            {/* Content */}
            <div className="prose prose-gray dark:prose-invert max-w-none">
              <section className="mb-12">
                <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
                <p className="mb-4">
                  By accessing and using PlanetScale AI App Factory (&quot;Service&quot;), you accept and agree 
                  to be bound by the terms and provision of this agreement. If you do not agree to 
                  abide by the above, please do not use this service.
                </p>
              </section>

              <section className="mb-12">
                <h2 className="text-2xl font-semibold mb-4">2. Use License</h2>
                <p className="mb-4">
                  Permission is granted to temporarily access and use the Service for personal, 
                  non-commercial transitory viewing only. This is the grant of a license, not a 
                  transfer of title, and under this license you may not:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Modify or copy the materials</li>
                  <li>Use the materials for any commercial purpose or for any public display</li>
                  <li>Attempt to reverse engineer any software contained in the Service</li>
                  <li>Remove any copyright or other proprietary notations from the materials</li>
                </ul>
              </section>

              <section className="mb-12">
                <h2 className="text-2xl font-semibold mb-4">3. Beta Program</h2>
                <p className="mb-4">
                  The Service is currently in beta. By participating in the beta program, you acknowledge that:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>The Service may contain bugs, errors, and other problems</li>
                  <li>The Service is provided &quot;as is&quot; without any warranties</li>
                  <li>We may discontinue the beta program at any time</li>
                  <li>Features may be added, modified, or removed without notice</li>
                </ul>
              </section>

              <section className="mb-12">
                <h2 className="text-2xl font-semibold mb-4">4. Generated Content</h2>
                <p className="mb-4">
                  Applications and code generated by the Service are subject to the following terms:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>You retain ownership of the applications you create using the Service</li>
                  <li>We do not claim any rights to your generated applications</li>
                  <li>You are responsible for ensuring your applications comply with all applicable laws</li>
                  <li>We are not liable for any issues arising from the use of generated applications</li>
                </ul>
              </section>

              <section className="mb-12">
                <h2 className="text-2xl font-semibold mb-4">5. Limitations</h2>
                <p className="mb-4">
                  In no event shall PlanetScale AI or its suppliers be liable for any damages 
                  (including, without limitation, damages for loss of data or profit, or due to 
                  business interruption) arising out of the use or inability to use the Service, 
                  even if PlanetScale AI or a PlanetScale AI authorized representative has been 
                  notified orally or in writing of the possibility of such damage.
                </p>
              </section>

              <section className="mb-12">
                <h2 className="text-2xl font-semibold mb-4">6. Modifications</h2>
                <p className="mb-4">
                  PlanetScale AI may revise these terms of service at any time without notice. 
                  By using this Service, you are agreeing to be bound by the then current version 
                  of these terms of service.
                </p>
              </section>

              <section className="mb-12">
                <h2 className="text-2xl font-semibold mb-4">7. Governing Law</h2>
                <p className="mb-4">
                  These terms and conditions are governed by and construed in accordance with the 
                  laws of the United States and you irrevocably submit to the exclusive jurisdiction 
                  of the courts in that State or location.
                </p>
              </section>

              <section className="mb-12">
                <h2 className="text-2xl font-semibold mb-4">8. Contact Information</h2>
                <p className="mb-4">
                  If you have any questions about these Terms of Service, please contact us at:
                </p>
                <ul className="list-none space-y-2">
                  <li>
                    <strong>Email:</strong>{' '}
                    <a href="mailto:legal@planetscale-ai.com" className="text-primary hover:underline">
                      legal@planetscale-ai.com
                    </a>
                  </li>
                  <li>
                    <strong>Address:</strong> PlanetScale AI, Inc.<br />
                    123 AI Boulevard<br />
                    San Francisco, CA 94105<br />
                    United States
                  </li>
                </ul>
              </section>
            </div>

            {/* Back to top */}
            <div className="mt-12 text-center">
              <Button
                variant="outline"
                onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
              >
                Back to top
              </Button>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}