/**
 * Fly.io Configuration Template Generator
 *
 * Generates optimized fly.toml configuration for generated apps.
 * Configured for Node.js/Vite+Express monolith deployment.
 */

export interface FlyTomlOptions {
  appName: string;
  region?: string;
  port?: number;
  enableHealthCheck?: boolean;
}

/**
 * Generate fly.toml configuration for a generated app
 *
 * @param options - Configuration options
 * @returns Complete fly.toml file content
 */
export function generateFlyToml(options: FlyTomlOptions): string {
  const {
    appName,
    region = 'sjc', // San Jose - good default for US West
    port = 3000,
    enableHealthCheck = true,
  } = options;

  const healthCheckConfig = enableHealthCheck ? `
  # Health checks
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"` : '';

  return `# Fly.io Configuration
# Generated by App-Gen-SaaS
# https://fly.io/docs/reference/configuration/

app = "${appName}"
primary_region = "${region}"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "${port}"

# Service configuration
[[services]]
  internal_port = ${port}
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  # Concurrency limits
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  # HTTP ports
  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true  # Redirect HTTP to HTTPS

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443${healthCheckConfig}
`;
}

/**
 * Generate README content for deployment instructions
 */
export function generateDeploymentReadme(appName: string, githubUrl: string): string {
  return `# ${appName}

Generated by [Leo](https://leo.ai)

## 🚀 One-Command Deploy to Fly.io

This app is **production-ready** with pre-configured Docker + Fly.io deployment.

### Prerequisites

1. **Install Fly.io CLI:**
   \`\`\`bash
   curl -L https://fly.io/install.sh | sh
   \`\`\`

2. **Sign up / Log in to Fly.io** (free tier available):
   \`\`\`bash
   flyctl auth login
   \`\`\`

### Deploy (Literally One Command!)

1. **Clone this repository:**
   \`\`\`bash
   git clone ${githubUrl}
   cd ${appName}
   \`\`\`

2. **Deploy:**
   \`\`\`bash
   flyctl launch --now
   \`\`\`

   The \`--now\` flag deploys immediately without prompting.

3. **Your app is live!** 🎉
   \`\`\`
   https://${appName}.fly.dev
   \`\`\`

### What Just Happened?

Fly.io:
- Read the included \`Dockerfile\` (multi-stage build for optimization)
- Read the \`fly.toml\` configuration (pre-configured for your app)
- Built your Docker image in the cloud
- Deployed to a free-tier machine with auto-scaling
- Provisioned HTTPS certificate
- Set up health checks

No manual configuration needed!

### Configuration Files Included

✅ **Dockerfile** - Multi-stage production build
  - Stage 1: Builds React frontend (Vite)
  - Stage 2: Prepares Node.js dependencies
  - Stage 3: Production runtime (optimized, non-root user)

✅ **fly.toml** - Fly.io deployment config
  - Auto-scaling from 0 machines (free tier friendly)
  - HTTPS with automatic certificates
  - Health checks (\`/health\` endpoint)
  - Production environment variables

✅ **.dockerignore** - Excludes unnecessary files from build
  - Faster builds
  - Smaller Docker images

### Manual Deployment Steps (if needed)

If you want more control:

\`\`\`bash
# Build locally first (optional)
docker build -t ${appName} .

# Deploy with custom settings
flyctl launch  # Interactive mode

# Scale machines
flyctl scale count 2

# View logs
flyctl logs

# SSH into machine
flyctl ssh console
\`\`\`

### Environment Variables

If your app needs environment variables (database URLs, API keys):

\`\`\`bash
# Set secrets (encrypted at rest)
flyctl secrets set DATABASE_URL=postgresql://...
flyctl secrets set API_KEY=your-key

# View secrets (names only, values hidden)
flyctl secrets list
\`\`\`

### Local Development

Run locally to test before deployment:

\`\`\`bash
npm install
npm run dev
\`\`\`

Access at: http://localhost:3000

### Docker Testing (optional)

Test the Docker build locally:

\`\`\`bash
# Build image
docker build -t ${appName} .

# Run container
docker run -p 3000:3000 ${appName}

# Access at http://localhost:3000
\`\`\`

### Troubleshooting

**Build fails with "npm ERR!"**
- Check \`package.json\` has correct scripts
- Ensure all dependencies are listed
- Try: \`npm install\` locally first

**App crashes on Fly.io**
- Check logs: \`flyctl logs\`
- Verify PORT environment variable usage in code
- Check health endpoint: \`/health\` returns 200

**Can't access deployed app**
- Wait 1-2 minutes for initial deployment
- Check app status: \`flyctl status\`
- Verify machines are running: \`flyctl scale show\`

### Cost Estimate

Fly.io free tier includes:
- Up to 3 shared-cpu-1x machines
- 160GB outbound data transfer
- Automatic HTTPS certificates

This app uses:
- 1 machine (auto-scales to 0 when idle)
- ~256MB RAM
- Free tier: **$0/month** (with low traffic)

See: https://fly.io/docs/about/pricing/

### Need Help?

- [Fly.io Documentation](https://fly.io/docs)
- [Leo Support](https://leo.ai/support)
- [Docker Best Practices](https://docs.docker.com/develop/dev-best-practices/)

---

**Generated:** ${new Date().toISOString()}
**Powered by:** Leo AI App Generator
`;
}
